stages:
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  AWS_DEFAULT_REGION: "ap-southeast-1"
  AWS_APP_NAME: "docker-react"
  AWS_ENV_NAME: "Docker-react-env"
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_KEY"
  S3_BUCKET_NAME: "elasticbeanstalk-ap-southeast-1-292185169872"
  S3_BUCKET_PATH: "docker-react"

test:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker build -t scarnyte/docker-react -f Dockerfile.dev .
  script:
    - docker run scarnyte/docker-react npm run test -- --coverage --watchAll=false

deploy:
  stage: deploy
  image: amazon/aws-cli:2.13.19
  script:
    # Create deployment package
    - zip -r deploy.zip .
    # Upload to S3 bucket/path
    - aws s3 cp deploy.zip s3://$S3_BUCKET_NAME/$S3_BUCKET_PATH/deploy-$CI_COMMIT_SHORT_SHA.zip
    # Register new app version in Elastic Beanstalk
    - aws elasticbeanstalk create-application-version \
        --application-name $AWS_APP_NAME \
        --version-label $CI_COMMIT_SHORT_SHA \
        --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=$S3_BUCKET_PATH/deploy-$CI_COMMIT_SHORT_SHA.zip
    # Update EB environment
    - aws elasticbeanstalk update-environment \
        --environment-name $AWS_ENV_NAME \
        --version-label $CI_COMMIT_SHORT_SHA
  only:
    - master
